# -*- coding: utf-8 -*-
"""Another copy of Fine-Tuning Local LLMs with Unsloth & Ollama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Li5ld7hQml18ebV_Rqx2DiRJ_adLHEZh
"""

!pip3 install unsloth

from unsloth import FastLanguageModel
model,tokenizer=FastLanguageModel.from_pretrained('gpt2',max_seq_length=2048,dtype=None,load_in_4bit=True)
model=FastLanguageModel.get_peft_model(r=64,target_modules=["q_proj",'k_proj','v_proj','o_proj','gate_proj','up_proj',
                                                          'down_proj'],model=model,lora_alpha=64*2,lora_dropout=0.1,bias='none',task_type='CAUSAL_LM',use_gradient_checkpointing=True)

import json
from dataset import Dataset
with open('dataset.json', 'r') as f:
    dataset = json.load(f)
    tuning_example=[]
    for example in data:
      tuning_example.append(f"<|user|>\n{example['prompt']}\n<|assistant|>\n{json.dumps(example['response'])}<|endoftext|>")
dataset=Dataset.from_dict(){'text':tuning_example}

def

##image





from trl import SFTTrainer,SFTConfig
trainer=SFTTrainer(model=model,train_dataset=dataset,tokenizer=tokenizer,dataset_text_field='text',max_seq_length=2048,args=SFTConfig(per_device_train_batch_size=2,gradient_accumulation_steps=4,warmup_steps=10,max_steps=60,num_train_epochs=3,logging_steps=1,output_dir='outputs',optim='adamw_8bit'))

trainer.train()

FastLanguageModel.for_inference(model)
message=[{'role':'user','content':'This is Sai. He loves NBA'}]
inputs=tokenizer.apply_chat_template(message,tokenize=True,add_generation_prompt=True,return_tensors='pt').to(model.device)
outputs=model.generate(input_ids=inputs,max_new_tokens=512,use_cache=True,temperature=0.7,do_sample=True,top_k=50,top_p=0.95)
response=tokenizer.batch_decode(outputs[0],skip_special_tokens=True)
print(response)

model.save_pretrained_gguf('finetuned_model',tokenizer,quantization_method='q4_k_m',maximum_memory_usage=0.3)

## download ollama
## ollama list
##ollama run finetunemodel

## people_data.json

[{
    "prompt": "What is the capital of France?",
    "response":{"name":"peter","age":23,"job":"Tour guide"
    }
    },
    {"prompt": "What is the capital of France?",
    "response":{"name":"peter","age":23,"job":"Tour guide"
    }}]